---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/aarna1wi/public_html/homebase
    - /usr/bin/npm install
    - /usr/bin/npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
